ribbon:
  eureka:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

server:
  port: 4000