ribbon:
  eureka:
    enabled: true
---
eureka:
  instance:
    appname: products-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
server:
  port: 4003

---
spring:
  profiles: products-service1
eureka:
  instance:
    appname: products-service
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone:  http://localhost:7777/eureka/
server:
  port: 5003
---
spring:
  profiles: products-service2
eureka:
  instance:
    appname: products-service
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone:  http://localhost:7777/eureka/
server:
  port: 6003
---
spring:
  profiles: products-service3
eureka:
  instance:
    appname: products-service
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone:  http://localhost:7777/eureka/
server:
  port: 7003